### ISSUE TITLE
feat-fe: 지원자 기본정보 상세 (모달 내부 왼쪽 부분) 

### ISSUE THREAD

**Issue by lurgi** [woowacourse-teams/2024-cruru#101]
## 목적
> 지원자 기본정보 상세 (모달 내부 왼쪽 부분) 빌드

## 작업 세부사항
- [x] Base Component (0)
- [x]  지원자 기본 정보 훅 (1)
- [x]  지원자 불합격 훅(1)
- [x]  Applicant Controls (2) Dropdown 부분입니다.
- [x]  Applicant Disqualify Button (2) 
- [x]  Applicant Details (2) 

## 참고 사항
-

> 아래의 별표줄 밑에  **요구사항 ID**만 작성해주세요. Prefix 금지!

********************
APP_BASE_DETAIL

**Comment by Chocochip101** [comment]
프로젝트와 마일스톤 설정 부탁드립니다.
