### ISSUE TITLE
chore-be: 모니터링 관련 환경 변수 추가

### ISSUE THREAD

**Issue by xogns1514** [woowacourse-teams/2024-cruru#222]
## 목적
> 모니터링 관련 환경 변수를 추가한다.

## 작업 세부사항
- [ ] docker-compose.dev.yml 파일에 모니터링 관련 환경 변수 추가
- [ ] CD docker workflow에 모니터링 관련 환경 변수 추가

## 참고 사항
- github dev 환경에 관련 secret 키 추가했습니다.
<img width="629" alt="image" src="https://github.com/user-attachments/assets/5dc9664f-d0bf-42c8-8140-74f67b3f7ee8">

 - MONITORING_BINDING_PORT
 - MONITORING_PORT
 - MONITORING_BASE_PATH

> 아래의 별표줄 밑에  **요구사항 ID**만 작성해주세요. Prefix 금지!

********************
DEV_MONITORING_02

**Comment by Chocochip101** [comment]
이슈 제목 컨벤션 확인해주세요.
