### ISSUE TITLE
refactor-be: ApplyForm Service 계층 파사드 패턴 적용 제안 & 예시

### ISSUE THREAD

**Issue by Dobby-Kim** [woowacourse-teams/2024-cruru#258]
## 목적

현재 Dashboard와 ApplyForm 도메인은 전반적인 엔티티 데이터 조회 및 생성 flow의 첫 단계로 사용되고 있습니다.
현재 하위 도메인(`process`, `question`, `answer` 등)의 데이터 처리를 ApplyForm의 Service에서  직접 다 처리하고 있습니다. 이는 ApplyForm 패키지 내부에 생성된 DTO 목록을 보시면 다른 도메인 패키지에 위치하고 있어야하는 클래스명이 대부분인 것을 통해 확인할 수 있습니다.

이와 다르게 Dashboard의 파사드 서비스에서는 하위 도메인 Service 계층이 그 역할을 맡아 대시보드 파사드가 모듈화된 하위 서비스 계층의 기능을 뽑아 쓰고 있습니다.

둘의 flow와 하위 도메인 처리 로직이 비슷하고 중복되는 것이 많습니다. 따라서 각각의 하위 도메인 서비스에 역할을 전적으로 부여하는 것을 제안합니다. 역할을 분리한 후, flow의 최상단에 위치한 Dashboard, ApplyForm 도메인은 파사드 서비스로 설계하여 하위 도메인의 모듈화된 service기능들을 적절히 재사용하는 예시를 작성해보았습니다.

## 작업 세부사항
- [x] ApplyForm Service가 의존하고 있는 하위 도메인 레포지토리 클래스 분리
- [x] 각 하위 도메인 Service에 ApplyForm Service에서 분리된 기능을 재배치
- [x] ApplyForm Facade 구현 
- [x] `process`, `question`, `answer` 관련 DTO 패키지 분리

## 참고 사항
- 초코칩(@Chocochip101 )이 진행 중인 be-251-FORM_QUES_READ_01 branch의 하위 브랜치로 코드 작성을 진행하였습니다.

********************
be-251-FORM_QUES_READ_01-1

**Comment by Chocochip101** [comment]
이전 리뷰에서 이야기가 길어지면 depth가 깊어져서 고민했는데, 관련 이슈 생성해주셔서 감사합니다 도비 👍
파사드를 다루는 리뷰에서 승인한 팀원이 러쉬와 명오이기 떄문에, @cutehumanS2 도 멘션하겠습니다!
