### ISSUE TITLE
chore-be: Ngnix docker container로 관리하도록 변경

### ISSUE THREAD

**Issue by xogns1514** [woowacourse-teams/2024-cruru#309]
## 목적
>  Ngnix를 docker container로 관리하도록 변경한다.

## 작업 세부사항
- [ ] Ngnix docker-compose.yml 작성
- [ ] 기존 Ngnix 설정 마이그레이션
- [ ] https 설정

## 참고 사항
-

> 아래의 별표줄 밑에  **요구사항 ID**만 작성해주세요. Prefix 금지!

********************

**Comment by Chocochip101** [comment]
이슈 제목 확인해주세요.
