### ISSUE TITLE
feat-be: DataSource Routing을 통한 DB Read/Write 요청 분산

### ISSUE THREAD

**Issue by xogns1514** [woowacourse-teams/2024-cruru#703]
## 목적
> read 트랜잭션, write 트랜잭션에 따른 DB routing 분리

## 작업 세부사항
- [ ] prod profile database yml 정보 변경
- [ ] prod profile의 변경된 DB 정보 githubSecret에 작성
- [ ] prod 서버 CD시, 두개의 DB 정보를 포함한 .env 파일을 만들도록 변경
- [ ] DB routing 분리를 위한 codebase 변경

## 참고 사항
-

> 아래의 별표줄 밑에  **요구사항 ID**만 작성해주세요. Prefix 금지!

********************
DB_ROUTING_01

**Comment by Chocochip101** [comment]
Issue 제목을 확인해주세요.
